config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  #Session
  get "/login" => "session#new", :as => 'login'
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

  # Home
  get '/home' => 'pages#home'

  #Dashboard
  get '/dashboards' => 'dashboards#index'

  get "/users/edit" => 'users#edit', :as => 'edit_user'

  get "/search" => 'dashboards#search'

  resources :users, :except => [:edit] do
    member do
      get :following, :followers
    end
  end

  get "/users/:id/follow" => "users#follow", :as => 'follow_user'
  resources :relationships, only: [:create, :destroy]

  resources :goals do
    resources :steps
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  password_digest :text
#  jarsCollection  :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  dashboard_id    :integer
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :goals
  belongs_to :dashboard

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # Follows a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  #Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #Returns true if the current suer is following the other user
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorise, :only => [:edit, :update, :following, :followers]

  def index
    @current_user = User.find_by :id => session[:user_id]
    @users = User.all
  end

  def show
    @user = User.find_by :id => params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @user.profile_picture = req["public_id"]
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = @current_user
  end

  def update
    @user = @current_user

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      @user.profile_picture = req["public_id"]


    # @user.assign_attribtues(user_params)
    @user.save
    end

    # redirect_to(user_path(@user))

    if @user.update (user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    user = @current_user
    user.destroy
    redirect_to root_path()
  end


  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    # @users = @user.followers.paginate(page: params[:page] || 1)
    render 'show_follow'
  end

  private

  def user_params
    params.required(:user).permit(:email, :name, :password, :password_confirmation)
  end

  def authorise
    unless @current_user.present?
      flash[:error] = "You need to be logged in to do that"
      redirect_to login_path()
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(@current_user.active_relationships.build ) do |f| %>
  <%= f.hidden_field "followed_id", :value => params[:id] %>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

<!-- <input id="follower_id" name="followed_id" type="hidden" value="3" /> -->

app/views/users/_follow_form.html.erb
<%# unless @current_user.present? %>
  <div id="follow_form">
    <% if @current_user.following?(@user) %>
      <%= render :partial => 'unfollow' %>
    <% else %>
      <%= render :partial => 'follow' %>
    <% end %>
  </div>
<%# end %>

app/views/users/_form.html.erb
<% unless @user.errors.full_messages.empty? %>
<ul>
  <% @user.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<%= form_for(@user, :html => {:multipart => true}) do |f| %>
<%#= form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email, :required => true %>
  </p>

  <p>
    <%= f.label "Profile Picture" %>
    <%= f.cl_image_upload :profile_picture, :required => true %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password, :required => true %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :required => true %>
  </p>

  <!-- <p>
    <%#= f.label :image %>
    <%#= f.cl_image_tag :image %>
  </p> -->

<%= f.submit %>
<% end %>

app/views/users/_stats.html.erb
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>

  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>

</div>

app/views/users/_unfollow.html.erb
<%= form_for(@current_user.active_relationships.find_by(followed_id: @user.id), html: {method: :delete}) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h3>Edit User</h3>

<%= render :partial => 'form' %>

<%= link_to "Delete User", user_path(@user), :method => :delete, :data => {:confirm => "Are you sure?"} %>
</div>

app/views/users/index.html.erb
<div class="all_user">
<% if @current_user.present? %>

  <div class="col s12 m7">
      <h5 class="header"><%= @current_user.name %> (You)</h5>
      <div class="card horizontal">
        <div class="card-image profile_picture">
            <%= cl_image_tag(@current_user.profile_picture, :class => "circle profile_picture") %>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <p><%= @current_user.email %></p>
            <p>Goals: <%= @current_user.goals.count %></p>
          </div>
          <div class="card-action">
            <%= link_to("Your profile", user_path(@current_user)) %>
          </div>
        </div>
      </div>
    </div>


<br>
<br>

  <h5 class="other users">Other Users:</h5>

  <% @users.each do |u| %>
    <% if u.name != @current_user.name %>
    <%#= cl_image_tag(u.profile_picture) %>

    <div class="col s12 m7">
        <h5 class="header"><%= u.name %></h5>
        <div class="card horizontal">
          <div class="card-image">
              <%= cl_image_tag(u.profile_picture, :class => "circle profile_picture") %>
          </div>
          <div class="card-stacked">
            <div class="card-content">
              <p><%= u.email %></p>
              <p>Goals: <%= u.goals.count %></p>
            </div>
            <div class="card-action">
              <%= link_to("#{u.name}'s profile", user_path(u)) %>
            </div>
          </div>
        </div>
      </div>
    <br>
    <% end %>
  <% end %>

<% else %>

  <h3>All Users</h3>
  <% @users.each do |u| %>
  <div class="col s12 m7">
      <h5 class="header"><%= u.name %></h5>
      <div class="card horizontal">
        <div class="card-image">
            <%= cl_image_tag(u.profile_picture, :class => "circle profile_picture") %>
        </div>
        <div class="card-stacked">
          <div class="card-content">
            <p><%= u.email %></p>
            <p>Goals: <%= u.goals.count %></p>
          </div>
          <!-- <div class="card-action">
            <%#= link_to("#{u.name}'s profile", user_path(u)) %>
          </div> -->
        </div>
      </div>
    </div>

  <% end %>

<% end %>
</div>

app/views/users/new.html.erb
<h3>Sign Up</h3>

<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h3><%= @user.name %>'s Profile</h3>

<ul>
  <li>Email: <%= @user.email %></li>
  <li>Goals: <%= @user.goals.count %></li>
</ul>



  <section>
  <%= render :partial => 'stats' %>
  </section>

<% if @current_user.present? %>
<% if @user != @current_user%>
  <div class="col-md-8">
    <%= render :partial => 'follow_form' %>
  </div>
<% end %>

<% if @user == @current_user %>

    <div class="controls">

      <%= link_to "Edit Profile", edit_user_path(@user) %>

  </div>
<% end %>
<% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>

<div class="row">
      <div class="col s6 m4">
            <section class="user_info">

              <h1>
                <%= @user.name %>
              </h1>
              <span>
                <%= link_to "View profile", @user %>
              </span>
              <span>
                <b>Goals: </b> <%= @user.goals.count %>
              </span>

      </section>
      <section class="stats">
            <%= render 'stats' %>
            <% if @users.any? %>
                  <% @users.each do |user| %>
                        <%= link_to "#{user.name}", user_path(user) %>
                  <% end %>
            <% end %>
      </section>
      </div>

      <!-- <div class="col s6 m4">
            <h3><%= @title %></h3>
            <%# if @users.any? %>
                  <ul class="users follow">
                  <%#= render @users%>
                  </ul>
                  <%#= will_paginate %>
            <%# end %>
      </div> -->
</div>