config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  #Session
  get "/login" => "session#new", :as => 'login'
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

  # Home
  get '/home' => 'pages#home'

  #Dashboard
  get '/dashboards' => 'dashboards#index'

  get "/users/edit" => 'users#edit', :as => 'edit_user'

  get "/search" => 'dashboards#search'

  resources :users, :except => [:edit] do
    member do
      get :following, :followers
    end
  end

  get "/users/:id/follow" => "users#follow", :as => 'follow_user'
  resources :relationships, only: [:create, :destroy]

  resources :goals do
    resources :steps
  end

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  name       :text
#  deadline   :datetime
#  categories :text
#  reward     :text
#  jar        :integer
#  image      :text
#  user_id    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base
  belongs_to :user
  has_many :steps
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    unless @current_user.present?
      @goals = Goal.all
    else
      @goals = @current_user.goals
    end
  end

  def show
    @goal = Goal.find_by :id => params[:id]
    @goal_steps = @goal.steps.order(:created_at)
    @new_step = @goal.steps.new

  end

  def new
    @goal = Goal.new
  end

  def create
    # @goal = Goal.create goal_params
    @goal = @current_user.goals.create goal_params
    redirect_to new_goal_step_path(@goal)
  end

  def edit
    @goal = Goal.find_by :id => params[:id]
  end


  def update
    goal = Goal.find_by :id => params[:id]
    goal.update goal_params
    redirect_to "/goals/#{goal.id}"
  end

  def destroy
    goal = Goal.find_by :id => params[:id]
    goal.destroy

    redirect_to goals_path
  end


  private
  def goal_params
    params.require(:goal).permit(:name, :categories, :deadline, :image, :reward, :user_id)
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for @goal do |g| %>
  <p>
    Goal: <%= g.text_field :name, :placeholder => "Goal", :required => true %>
  </p>

  <p>
    Cateogory: <%= g.text_field :categories, :placeholder => "Cateogory", :required => true %>
  </p>

  <p>
    Reward: <%= g.text_field :reward, :placeholder => "Reward" %>
  </p>

  <p>
    Deadline: <%= g.date_field :deadline, :placeholder => "Deadline?" %>
  </p>

  <p>
    Image: <%= g.text_field :image, :placeholder => "Image URL" %>
  </p>

<%= g.submit %>
<% end %>

app/views/goals/edit.html.erb
<h3>Edit Goal</h3>

<%= render :partial => 'form' %>

app/views/goals/index.html.erb
<h3>All Goals</h3>

<% unless @current_user.present? %>
<p>Sign in to view your goals</p>

<% else %>

<div class="row">
  <% @goals.each do |g| %>

      <div class="col s12 m4">
          <div class="card">
              <div class="card-image waves-effect waves-block waves-light">
                  <div class="activator"><%= image_tag "work.jpg"%></div>
                  <!-- <img class="activator" src="work.jpg"> -->
              </div>
              <div class="card-content">
                  <span class="card-title activator grey-text text-darken-4"><%= g.name %>
                      <i class="material-icons right">more_vert</i>
                  </span>
                  <p><%= link_to("Edit Goal", "/goals/#{g.id}") %></p>
              </div>
              <div class="card-reveal">
                  <span class="card-title grey-text text-darken-4"><%= g.name %>
                      <i class="material-icons right">close</i>
                  </span>
                  <%g.steps.each do |s| %>
                  <ul>
                      <li><%= s.name %></li>
                  </ul>

                  <% end %>
              </div>
          </div>
      </div>

  <% end %>
</div>

<%# @goals.each do |g| %>
<!-- <ul>
      <li> <%#= link_to(g.name, "/goals/#{g.id}") %> </li>
    </ul> -->
<%# end %>

<%= month_calendar(events: @goals, attribute: :deadline) do |date, goals| %>
<%= date.day %>
<% goals.each do |goal| %>
<div>
    <%= link_to(goal.name, goal_path(goal)) %>
</div>
<% end %>
<% end %>
<%end %>

app/views/goals/new.html.erb
<h3>New Goal</h3>

<%= render :partial => 'form' %>

app/views/goals/show.html.erb
<h3><%= @goal.name %></h3>

<h5>Reward: <%= @goal.reward %></h5>
<ul>
  <% @goal_steps.each do |s| %>
      <li><%= s.name %> <%= link_to( "Delete Step", goal_step_path( :id => s, :goal_id => @goal.id ), :method => "delete" ) %></li>
  <% end %>
</ul>

<%= form_for @new_step, :url => goal_steps_path( @goal ) do |s| %>
<p>
  Step: <%= s.text_field :name, :placeholder => "Step"%>
  <%= s.submit %>
</p>
<% end %>

<br>
<br>

<div class="controls">
  <button><%= link_to "Edit Goal", edit_goal_path(@goal) %> </button>
  <button><%= link_to "Delete Goal", goal_path(@goal), :method => :delete, :data => {:confirm => "Are you sure?"} %></button>
</div>

<%#= link_to "Create Step", new_goal_step_path(@goal) %>