config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  #Session
  get "/login" => "session#new", :as => 'login'
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

  # Home
  get '/home' => 'pages#home'

  #Dashboard
  get '/dashboards' => 'dashboards#index'

  get "/users/edit" => 'users#edit', :as => 'edit_user'

  get "/search" => 'dashboards#search'

  resources :users, :except => [:edit] do
    member do
      get :following, :followers
    end
  end

  get "/users/:id/follow" => "users#follow", :as => 'follow_user'
  resources :relationships, only: [:create, :destroy]

  resources :goals do
    resources :steps
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rozella</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= cloudinary_js_config %>

</head>
<body class="<%= params[:controller] %> <%= params[:action] %>">

<nav>
  <div>
    <!-- <a href="#" class="brand-logo">Logo</a> -->

    <li class="brand-logo"><%= link_to "Rozella", root_path %></li>
    <ul id="nav-mobile" class="right hide-on-med-and-down">


    <% unless @current_user.present? %>
    <li><%= link_to "All Users", users_path %> </li>
      <li><%= link_to "Sign Up", new_user_path %> </li>
      <li><%= link_to "Login", login_path %> </li>
    <% else %>
      <li><%= link_to "All Users", users_path %> </li>
      <li><%= link_to "Profile", user_path(@current_user) %> </li>
      <li><%= link_to "Dashboard", dashboards_path %> </li>
      <li><%= link_to "My Goals", goals_path %> </li>
      <li><%= link_to "New Goal", new_goal_path %> </li>
      <!-- <li><%#= link_to "Edit Profile", edit_user_path %> </li> -->
      <li><%= link_to "Log Out", login_path, :method => :delete %> </li>
    <%end %>
    </ul>
  </div>
</nav>


<div class="container">
<%= yield %>
</div>


<footer>
  <div class="footer">
    @2016 Rozen. All rights reserved.
  </div>
</footer>

</body>
</html>